# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b30b1f086a25dd3eaed3c474928d684275696a2c537e5efe52c79315cff08146a9cd430c0af2d990e78ea098d2e70631154a7ad0651cf2156de980c0b51d5f4

test:
  secret_key_base: 971b39d8508ed36bbc9a058f8e7c1448961956edfa2ef4daa274a733110ba55f7457cd8126a2a3f36b9b59f68350392f0cf029459204672a17125c2779d9e3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
